# Site settings
name: 熊本随心的博客
email: amerthyst@126.com
author: Drizzle
url: https://drizzleing.github.io
resume_site: https://drizzleing.github.io
github: https://github.com/drizzleing/
baseurl:
description: Record every bit of growth
meta_description: 熊本随心;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: drizzleing

# Build settings
markdown: kramdown

baidu_analysis: 9081dbacf8832c71535665342568bf77
